name: Proxy Scraper Job 
on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 
jobs: 
  scrape-proxies: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
        with:
          token: ${{ secrets.MY_PAT }}
          ref: main
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt 
      - name: Run proxy scraper script 
        run: python scripts/Proxy.py 
      - name: Commit and push changes 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxy.txt
          git commit -m "Update proxy list [skip ci]"
          git push origin main
